/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.veterinaria.vsitaGraf;

import javax.swing.table.DefaultTableModel;
import org.carlosaltan.veterinaria.controlador.ControladorMascota;
import javax.swing.table.TableModel;
import org.carlosaltan.veterinaria.modelo.MascotaModelo;

/**
 * JInternalFrame para ver las mascotas 
 * @author Carlos Altán
 * @version 1.0
 */
public class VistaVerMascota extends javax.swing.JInternalFrame {
public ControladorMascota controlador = ControladorMascota.getInstancia(); 
    /**
     * Creates new form VistaVerMascota
     */
    public VistaVerMascota() {
        initComponents();
    }
    
    public void mostrarDatos(){
        
        String [] encabezados = {"id", "dueno", "Nombre", "DPI", "Tipo", "Raza", "Edad", "Razon"}; 
        int cantidadDeElementos = controlador.cantiadadDeMascotas(); 
        DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
        jTable1.setModel(cabeceraDeTabla);  
        TableModel listaDeDatos  = jTable1.getModel();  
        for (int i = 0; i< cantidadDeElementos; i++ ){
            MascotaModelo empleado = controlador.mostarMascota().get(i);
            listaDeDatos.setValueAt(empleado.getId(), i, 0); 
            listaDeDatos.setValueAt(empleado.getDueno(), i, 1);
            listaDeDatos.setValueAt(empleado.getNombre(), i, 2);
            listaDeDatos.setValueAt(empleado.getIdDueno(), i, 3);
            listaDeDatos.setValueAt(empleado.getTipo(), i, 4);
            listaDeDatos.setValueAt(empleado.getRaza(), i, 5);
            listaDeDatos.setValueAt(empleado.getEdad(), i, 6);
            listaDeDatos.setValueAt(empleado.getRazonDeCita(), i, 7);
            
   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Dueño", "Nombre", "DPI", "Tipo", "Raza", "Edad", "Razon"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
