/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.veterinaria.vsitaGraf;
import org.carlosaltan.veterinaria.modelo.ClienteModelo; 
import org.carlosaltan.veterinaria.controlador.ControladorCliente; 
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *JInternalFrame para ver los clientes 
 * @author Carlos Altán
 */
public class VistaVerCiente extends javax.swing.JInternalFrame {
public ControladorCliente controlador = ControladorCliente.getInstancia(); 
    /**
     * Creates new form VistaVerCiente
     */
    public VistaVerCiente() {
        initComponents();
    }
    
    public void mostrarDatos(){
        
        String [] encabezados = {"id", "Nombre", "Telefono", "Email", "DPI", "No.Mascotas"}; 
        int cantidadDeElementos = controlador.cantidadDeClientes(); 
        DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
        jTable1.setModel(cabeceraDeTabla);  
        TableModel listaDeDatos  = jTable1.getModel();  
        for (int i = 0; i< cantidadDeElementos; i++ ){
            ClienteModelo cliente = controlador.mostarCliente().get(i);
            listaDeDatos.setValueAt(cliente.getId(), i, 0); 
            listaDeDatos.setValueAt(cliente.getNombre(), i, 1);
            listaDeDatos.setValueAt(cliente.getTelefono(), i, 2); 
            listaDeDatos.setValueAt(cliente.getEmail(), i, 3);
            listaDeDatos.setValueAt(cliente.getIdPersonal(), i, 4);
            listaDeDatos.setValueAt(cliente.getNoMascotas(), i, 5);
   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Email", "DPI", "No.Mascotas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
