/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.veterinaria.vsitaGraf;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.carlosaltan.veterinaria.controlador.ControladorCita;
import org.carlosaltan.veterinaria.modelo.CitasModelo;
/**
 * JInternalFrame para ver las citas 
 * @author Carlos Altán
 * @version 1.0
 */
public class VistaVerCita extends javax.swing.JInternalFrame {

    public ControladorCita controlador = ControladorCita.getInstancia(); 
    /**
     * Creates new form VistaVerCita
     */
    public VistaVerCita() {
        initComponents();
    }
    
     public void mostrarDatos(){
        
        String [] encabezados = {"id", "Nombre Persona", "DPI", "Fecha", "Hora", "Razon", "Cantidad de Mascotas"}; 
        int cantidadDeElementos = controlador.cantiadadDeCitas(); 
        DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
        jTable1.setModel(cabeceraDeTabla);  
        TableModel listaDeDatos  = jTable1.getModel();  
        for (int i = 0; i< cantidadDeElementos; i++ ){
            CitasModelo cliente = controlador.mostrarCita().get(i);
            listaDeDatos.setValueAt(cliente.getId(), i, 0); 
            listaDeDatos.setValueAt(cliente.getNombrePersona(), i, 1);
            listaDeDatos.setValueAt(cliente.getIdPersona(), i, 2); 
            listaDeDatos.setValueAt(cliente.getFecha(), i, 3);
            listaDeDatos.setValueAt(cliente.getHora(), i, 4);
            listaDeDatos.setValueAt(cliente.getRazon(), i, 5);
            listaDeDatos.setValueAt(cliente.getCantidadDemascotas(), i, 6);
            
   
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Persona", "DPI", "Fecha", "Hora", "Razon", "Cantidad de Mascotas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
