/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.veterinaria.vsitaGraf;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.carlosaltan.veterinaria.controlador.ControladorEmpleado;
import org.carlosaltan.veterinaria.modelo.EmpleadoModelo;

/**
 *JInternalFrame para ver empleado 
 * @author Carlos Altán
 */
public class VistaVerEmpleado extends javax.swing.JInternalFrame {
public ControladorEmpleado controlador = ControladorEmpleado.getInstancia(); 
    /**
     * Creates new form VistaVerEmpleado
     */
    public VistaVerEmpleado() {
        initComponents();
    }
    
    public void mostrarDatos(){
        
        String [] encabezados = {"id", "Nombre", "Telefono", "Email", "Tipo", "Area", "Direccion", "Carne"}; 
        int cantidadDeElementos = controlador.cantidadDeEmpleados(); 
        DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeElementos);
        jTable1.setModel(cabeceraDeTabla);  
        TableModel listaDeDatos  = jTable1.getModel();  
        for (int i = 0; i< cantidadDeElementos; i++ ){
            EmpleadoModelo empleado = controlador.mostarEmpleado().get(i);
            listaDeDatos.setValueAt(empleado.getId(), i, 0); 
            listaDeDatos.setValueAt(empleado.getNombre(), i, 1);
            listaDeDatos.setValueAt(empleado.getTelefono(), i, 2); 
            listaDeDatos.setValueAt(empleado.getEmail(), i, 3);
            listaDeDatos.setValueAt(empleado.getTipo(), i, 4);
            listaDeDatos.setValueAt(empleado.getArea(), i, 5);
            listaDeDatos.setValueAt(empleado.getDireccion(), i, 6);
            listaDeDatos.setValueAt(empleado.getCarne(), i, 7);
            
   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Telefono", "Email", "Tipo", "Area", "Direccion", "Carne"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
